server:
  port: 6200
  contextPath: /tng-vnv-tee
spring.jackson.property-naming-strategy: SNAKE_CASE
api:
  name: 5GTANGO VnV Platform Test Execution Engine
  description: An H2020 5GTANGO project
  version: 0.0.1
  host: tng-vnv-tee:6200
  terms.url: https://5gtango.eu/
  license:
    name: Apache License 2.0
    url: https://github.com/sonata-nfv/tng-vnv-tee/blob/master/LICENSE
app:
  tee.tmp.dir: /workspace
  gk:
    host: ${app_gk_base_url}
    base.url: http://${app.gk.host}:32002/api/v3
    session:
      endpoint: ${app.gk.base.url}/sessions
      username: sonata
      password: 1234
  vnvgk:
    host: tng-api-gtw
    base.url: http://${app.vnvgk.host}:5000/api/v3
  cat:
    host: tng-cat
    base.url: http://${app.cat.host}:4011/api/catalogues/v2
    package.metadata.endpoint: ${app.vnvgk.base.url}/packages/{packageId}
    test.list.endpoint: ${app.cat.base.url}/tests
    test.metadata.endpoint: ${app.cat.base.url}/tests/{testUuid}
    test.suite.load.endpoint: ${app.cat.base.url}/test-suites/{testUuid}
    resource.download.endpoint: ${app.vnvgk.base.url}/packages/{packageId}/files/{resourceUuid}
  sp:
    service.list.endpoint: ${app.gk.base.url}/services
  trr:
    host: tng-rep
    base.url: http://${app.trr.host}:4012/trr
    test.suite.result.create.endpoint: ${app.trr.base.url}/test-suite-results
    test.suite.result.update.endpoint: ${app.trr.base.url}/test-suite-results/{uuid}
    test.suite.result.filter.by.service.endpoint: ${app.trr.base.url}/test-suite-results?service_uuid={service_uuid}
    test.suite.result.filter.by.test.endpoint: ${app.trr.base.url}/test-suite-results?test_uuid={test_uuid}
    network.service.instance.load.endpoint: ${app.gk.base.url}/records/services/{instanceUuid}
    network.function.instance.load.endpoint: ${app.gk.base.url}/records/functions/{networkFunctionInstanceId}
